namespace Eternar.Core
{
    public enum PedAttribute : int
    {
        Health,
        Stamina,
        SpecialAbility,
        Courage,
        Agility,
        Speed,
        Acceleration,
        Bonding,
        Hunger,
        Fatigued,
        Inebriated,
        Poisoned,
        BodyHeat,
        BodyWeight,
        Overfed,
        Sickness,
        Dirtiness,
        DirtinessHat,
        Strength,
        Grit,
        Instinct,
        Unruliness,
        DirtinessSkin
    };
}